// ============================================================
// Mock 数据 —— 衣物库 + 天气
// 阶段2：替换为 Unsplash 真实衣物照片，视觉更接近小红书/电商风
// 男士 12 件 / 女士 16 件，覆盖各类别 & 季节 & 风格
// ============================================================

import type { Item, Weather, Gender } from '../types';
import { PHOTO_LIB } from './wardrobe-photos';

/** 工具：生成稳定 ID */
const id = (prefix: string, n: number) => `${prefix}-${n.toString().padStart(3, '0')}`;

/** 女士 mock 衣橱 */
export const FEMALE_ITEMS: Item[] = [
  // —— 上装 ——
  {
    id: id('f-top', 1),
    photoUrl: PHOTO_LIB.tshirt_white,
    category: 'top',
    subCategory: '基础白T',
    color: '#f5f1ea',
    colorFamily: 'white',
    pattern: 'solid',
    season: 'all',
    styles: ['minimal', 'japanese'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 12,
  },
  {
    id: id('f-top', 2),
    photoUrl: PHOTO_LIB.shirt_stripe,
    category: 'top',
    subCategory: '条纹衬衫',
    color: '#dee5dc',
    colorFamily: 'cool',
    pattern: 'stripe',
    season: 'spring',
    styles: ['minimal', 'oldmoney'],
    dressCodes: ['smart-casual', 'formal'],
    wearCount: 6,
  },
  {
    id: id('f-top', 3),
    photoUrl: PHOTO_LIB.sweater_camel,
    category: 'top',
    subCategory: '驼色针织衫',
    color: '#d2a679',
    colorFamily: 'warm',
    pattern: 'solid',
    season: 'autumn',
    styles: ['oldmoney', 'minimal'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 9,
  },
  {
    id: id('f-top', 4),
    photoUrl: PHOTO_LIB.hoodie_black,
    category: 'top',
    subCategory: '黑色卫衣',
    color: '#1f1f1f',
    colorFamily: 'black',
    pattern: 'solid',
    season: 'autumn',
    styles: ['street', 'cool'],
    dressCodes: ['casual', 'sporty'],
    wearCount: 18,
  },
  // —— 下装 ——
  {
    id: id('f-bot', 1),
    photoUrl: PHOTO_LIB.jeans_blue,
    category: 'bottom',
    subCategory: '牛仔裤',
    color: '#5a7693',
    colorFamily: 'cool',
    pattern: 'denim',
    season: 'all',
    styles: ['street', 'minimal', 'y2k'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 22,
  },
  {
    id: id('f-bot', 2),
    photoUrl: PHOTO_LIB.skirt_black,
    category: 'bottom',
    subCategory: '黑色半身裙',
    color: '#2a2a2a',
    colorFamily: 'black',
    pattern: 'solid',
    season: 'all',
    styles: ['minimal', 'oldmoney', 'business'],
    dressCodes: ['smart-casual', 'formal'],
    wearCount: 8,
  },
  {
    id: id('f-bot', 3),
    photoUrl: PHOTO_LIB.pants_beige,
    category: 'bottom',
    subCategory: '米色阔腿裤',
    color: '#e8dcc4',
    colorFamily: 'warm',
    pattern: 'solid',
    season: 'spring',
    styles: ['minimal', 'oldmoney'],
    dressCodes: ['smart-casual', 'formal'],
    wearCount: 5,
  },
  // —— 连衣裙 ——
  {
    id: id('f-dress', 1),
    photoUrl: PHOTO_LIB.dress_floral,
    category: 'dress',
    subCategory: '法式碎花裙',
    color: '#c69a8e',
    colorFamily: 'warm',
    pattern: 'print',
    season: 'summer',
    styles: ['sweet', 'japanese'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 4,
  },
  {
    id: id('f-dress', 2),
    photoUrl: PHOTO_LIB.dress_black,
    category: 'dress',
    subCategory: '小黑裙',
    color: '#1a1a1a',
    colorFamily: 'black',
    pattern: 'solid',
    season: 'all',
    styles: ['minimal', 'cool', 'oldmoney'],
    dressCodes: ['smart-casual', 'formal'],
    wearCount: 7,
  },
  // —— 外套 ——
  {
    id: id('f-out', 1),
    photoUrl: PHOTO_LIB.blazer_navy,
    category: 'outer',
    subCategory: '海军蓝西装',
    color: '#3d4f5f',
    colorFamily: 'cool',
    pattern: 'solid',
    season: 'all',
    styles: ['business', 'oldmoney'],
    dressCodes: ['formal', 'smart-casual'],
    wearCount: 6,
  },
  {
    id: id('f-out', 2),
    photoUrl: PHOTO_LIB.coat_camel,
    category: 'outer',
    subCategory: '驼色大衣',
    color: '#c9b896',
    colorFamily: 'warm',
    pattern: 'solid',
    season: 'winter',
    styles: ['oldmoney', 'minimal'],
    dressCodes: ['smart-casual', 'formal'],
    wearCount: 10,
    waterproof: false,
  },
  {
    id: id('f-out', 3),
    photoUrl: PHOTO_LIB.puffer_black,
    category: 'outer',
    subCategory: '黑色羽绒服',
    color: '#2c3e50',
    colorFamily: 'cool',
    pattern: 'solid',
    season: 'winter',
    styles: ['street', 'cool'],
    dressCodes: ['casual', 'sporty'],
    wearCount: 14,
    waterproof: true,
  },
  // —— 鞋 ——
  {
    id: id('f-sh', 1),
    photoUrl: PHOTO_LIB.sneakers_white,
    category: 'shoes',
    subCategory: '小白鞋',
    color: '#fafafa',
    colorFamily: 'white',
    pattern: 'solid',
    season: 'all',
    styles: ['minimal', 'street', 'japanese'],
    dressCodes: ['casual', 'smart-casual', 'sporty'],
    wearCount: 30,
  },
  {
    id: id('f-sh', 2),
    photoUrl: PHOTO_LIB.boots_brown,
    category: 'shoes',
    subCategory: '棕色短靴',
    color: '#3a2820',
    colorFamily: 'warm',
    pattern: 'solid',
    season: 'autumn',
    styles: ['oldmoney', 'street'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 11,
  },
  // —— 配饰 ——
  {
    id: id('f-acc', 1),
    photoUrl: PHOTO_LIB.bag_brown,
    category: 'accessory',
    subCategory: '棕色手提包',
    color: '#3a2820',
    colorFamily: 'warm',
    pattern: 'solid',
    season: 'all',
    styles: ['oldmoney', 'minimal'],
    dressCodes: ['smart-casual', 'formal', 'casual'],
    wearCount: 16,
  },
  {
    id: id('f-acc', 2),
    photoUrl: PHOTO_LIB.scarf_red,
    category: 'accessory',
    subCategory: '羊毛围巾',
    color: '#b8635f',
    colorFamily: 'warm',
    pattern: 'check',
    season: 'winter',
    styles: ['oldmoney', 'japanese'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 4,
  },
];

/** 男士 mock 衣橱 */
export const MALE_ITEMS: Item[] = [
  // —— 上装 ——
  {
    id: id('m-top', 1),
    photoUrl: PHOTO_LIB.tshirt_white,
    category: 'top',
    subCategory: '基础白T',
    color: '#f5f1ea',
    colorFamily: 'white',
    pattern: 'solid',
    season: 'all',
    styles: ['minimal', 'street'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 18,
  },
  {
    id: id('m-top', 2),
    photoUrl: PHOTO_LIB.shirt_blue,
    category: 'top',
    subCategory: '蓝色衬衫',
    color: '#a8c5d6',
    colorFamily: 'cool',
    pattern: 'solid',
    season: 'all',
    styles: ['business', 'minimal', 'oldmoney'],
    dressCodes: ['formal', 'smart-casual'],
    wearCount: 10,
  },
  {
    id: id('m-top', 3),
    photoUrl: PHOTO_LIB.sweater_gray_m,
    category: 'top',
    subCategory: '深灰针织衫',
    color: '#3d3d3d',
    colorFamily: 'neutral',
    pattern: 'solid',
    season: 'autumn',
    styles: ['minimal', 'oldmoney'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 7,
  },
  {
    id: id('m-top', 4),
    photoUrl: PHOTO_LIB.hoodie_black,
    category: 'top',
    subCategory: '黑色卫衣',
    color: '#1a1a1a',
    colorFamily: 'black',
    pattern: 'solid',
    season: 'autumn',
    styles: ['street', 'cool'],
    dressCodes: ['casual', 'sporty'],
    wearCount: 22,
  },
  // —— 下装 ——
  {
    id: id('m-bot', 1),
    photoUrl: PHOTO_LIB.jeans_dark,
    category: 'bottom',
    subCategory: '深色牛仔裤',
    color: '#3d5269',
    colorFamily: 'cool',
    pattern: 'denim',
    season: 'all',
    styles: ['street', 'minimal'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 28,
  },
  {
    id: id('m-bot', 2),
    photoUrl: PHOTO_LIB.pants_black,
    category: 'bottom',
    subCategory: '黑色西裤',
    color: '#2a2a2a',
    colorFamily: 'black',
    pattern: 'solid',
    season: 'all',
    styles: ['business', 'oldmoney'],
    dressCodes: ['formal', 'smart-casual'],
    wearCount: 9,
  },
  {
    id: id('m-bot', 3),
    photoUrl: PHOTO_LIB.shorts_olive,
    category: 'bottom',
    subCategory: '牛仔短裤',
    color: '#a3c4dc',
    colorFamily: 'cool',
    pattern: 'solid',
    season: 'summer',
    styles: ['street', 'cool'],
    dressCodes: ['casual', 'sporty'],
    wearCount: 5,
  },
  // —— 外套 ——
  {
    id: id('m-out', 1),
    photoUrl: PHOTO_LIB.blazer_navy_m,
    category: 'outer',
    subCategory: '海军蓝西装',
    color: '#2c3e50',
    colorFamily: 'cool',
    pattern: 'solid',
    season: 'all',
    styles: ['business', 'oldmoney'],
    dressCodes: ['formal'],
    wearCount: 8,
  },
  {
    id: id('m-out', 2),
    photoUrl: PHOTO_LIB.jacket_leather,
    category: 'outer',
    subCategory: '皮夹克',
    color: '#3a2820',
    colorFamily: 'warm',
    pattern: 'solid',
    season: 'autumn',
    styles: ['street', 'cool'],
    dressCodes: ['casual', 'smart-casual'],
    wearCount: 6,
  },
  {
    id: id('m-out', 3),
    photoUrl: PHOTO_LIB.puffer_black,
    category: 'outer',
    subCategory: '黑色冲锋衣',
    color: '#1f1f1f',
    colorFamily: 'black',
    pattern: 'solid',
    season: 'winter',
    styles: ['street', 'cool'],
    dressCodes: ['casual', 'sporty'],
    wearCount: 12,
    waterproof: true,
  },
  // —— 鞋 ——
  {
    id: id('m-sh', 1),
    photoUrl: PHOTO_LIB.sneakers_white,
    category: 'shoes',
    subCategory: '小白鞋',
    color: '#fafafa',
    colorFamily: 'white',
    pattern: 'solid',
    season: 'all',
    styles: ['minimal', 'street'],
    dressCodes: ['casual', 'smart-casual', 'sporty'],
    wearCount: 35,
  },
  {
    id: id('m-sh', 2),
    photoUrl: PHOTO_LIB.shoes_oxford,
    category: 'shoes',
    subCategory: '黑色皮鞋',
    color: '#1f1612',
    colorFamily: 'black',
    pattern: 'solid',
    season: 'all',
    styles: ['business', 'oldmoney'],
    dressCodes: ['formal', 'smart-casual'],
    wearCount: 10,
  },
];

/** 按性别取衣橱 */
export function getMockItems(gender: Gender): Item[] {
  return gender === 'female' ? FEMALE_ITEMS : MALE_ITEMS;
}

/** 7 天 mock 天气（兜底用，真实接口失败时回退） */
export function getMockWeather(city: string = '上海', startDate?: Date): Weather[] {
  const start = startDate ?? new Date();
  const conditions: Weather['condition'][] = ['sunny', 'cloudy', 'cloudy', 'rainy', 'sunny', 'sunny', 'cloudy'];
  const highs = [22, 24, 21, 18, 23, 26, 25];
  const lows = [14, 16, 14, 12, 15, 18, 17];
  const uvs: Weather['uv'][] = ['medium', 'medium', 'low', 'low', 'high', 'high', 'medium'];
  return Array.from({ length: 7 }, (_, i) => {
    const d = new Date(start);
    d.setDate(d.getDate() + i);
    return {
      date: d.toISOString().slice(0, 10),
      tempHigh: highs[i],
      tempLow: lows[i],
      condition: conditions[i],
      uv: uvs[i],
      city,
    };
  });
}

/** 当前天气（首页卡片用，兜底） */
export function getTodayWeather(): Weather {
  return getMockWeather()[0];
}
